# left-side user profile
avatar: //image.xiaomo.info/logo/avatar.png
location: localhost
email: xiaomo@xiaomo.info
social:
  github: '//github.com/hoko'
  linkedin: '//www.linkedin.com/in/xiaomoinfo/'
  facebook: '//www.facebook.com/chinaHupeng'
  Email: "mailto:xiaomo@xiaomo.info"
  QQ: "http://wpa.qq.com/msgrd?v=3&uin=83387856&site=qq&menu=yes"
  Twitter: "https://twitter.com/xiaomoinfo"
  StackOverflow: "http://stackoverflow.com/users/5804125/hpbest"

# navbar menu
menu:
  archives: true
  tags: true
  categories: true

rss_dir: atom.xml

# widget
ga: # google analytics tracking code UA-XXXXXXX-X
baidutongji: # baidutongji tracking code
duoshuo: # duoshuo username
gsc: # google custom search code

# flagcounter
flagcounter_href: # https://info.flagcounter.com/xxxx
flagcounter_img_src: # https://s01.flagcounter.com/xxxx
