name: Deploy # workflow name

on:
  [push] # 触发事件

jobs:
  buildJob: # job1 id
    runs-on: ubuntu-latest # 运行环境为最新版 Ubuntu
    name: A job to deploy blog.
    steps:
    - name: Step1 Checkout # step1 获取源码
      uses: actions/checkout@v2 # 使用 actions/checkout@v2
         with:
          ref: ${{ github.head_ref }}

    # Caching dependencies to speed up workflows. (GitHub will remove any cache entries that have not been accessed in over 7 days.) 缓存压缩 node_modules，不用每次下载，使用时解压，可以加快工作流的执行过程，超过 7 天没有使用将删除压缩包。
    - name: Step2 Cache node modules # step2
      uses: actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Step3 Install Dependencies # step3 name
      if: steps.cache.outputs.cache-hit != 'true' # 如果变量 cache-hit 不等于 true
      run: npm install # 安装 node modules 相关依赖

    # Deploy hexo blog website.
    - name: Step4 Deploy # step4
      id: deploy
      uses: sma11black/hexo-action@v1.0.0
      with:
        deploy_key: ${{ secrets.DEPLOY_KEY }}
        user_name: houko
        user_email: xiaomo@xiaomo.info
        commit_msg: ${{ github.event.head_commit.message }}  # (or delete this input setting to use hexo default settings)
    - name: Step5 Get the output
      run: |
        echo "${{ steps.deploy.outputs.notify }}"
